### ISSUE TITLE
Camera Error

### ISSUE THREAD

**Issue by pradyotprksh** [UpReckless/PortraitCameraSupport#1]
Hello, I used your library for the camera. But I am getting this error:

12-28 16:47:18.833 27341-27341/prakash.pradyot.com.pinterestclone W/ArrayUtils: Ignoring invalid value manual
12-28 16:47:18.833 27341-27341/prakash.pradyot.com.pinterestclone W/ArrayUtils: Ignoring invalid value manual
12-28 16:47:18.834 27341-27341/prakash.pradyot.com.pinterestclone W/ArrayUtils: Ignoring invalid value emboss
12-28 16:47:18.834 27341-27341/prakash.pradyot.com.pinterestclone W/ArrayUtils: Ignoring invalid value sketch
12-28 16:47:18.834 27341-27341/prakash.pradyot.com.pinterestclone W/ArrayUtils: Ignoring invalid value neon
12-28 16:47:18.834 27341-27341/prakash.pradyot.com.pinterestclone W/ArrayUtils: Ignoring invalid value asd
12-28 16:47:18.834 27341-27341/prakash.pradyot.com.pinterestclone W/ArrayUtils: Ignoring invalid value backlight
12-28 16:47:18.834 27341-27341/prakash.pradyot.com.pinterestclone W/ArrayUtils: Ignoring invalid value flowers
12-28 16:47:18.834 27341-27341/prakash.pradyot.com.pinterestclone W/ArrayUtils: Ignoring invalid value AR
12-28 16:47:18.843 27341-27341/prakash.pradyot.com.pinterestclone W/ArrayUtils: Ignoring invalid value manual
12-28 16:47:18.844 27341-27341/prakash.pradyot.com.pinterestclone W/ArrayUtils: Ignoring invalid value emboss
12-28 16:47:18.844 27341-27341/prakash.pradyot.com.pinterestclone W/ArrayUtils: Ignoring invalid value sketch
12-28 16:47:18.844 27341-27341/prakash.pradyot.com.pinterestclone W/ArrayUtils: Ignoring invalid value neon
12-28 16:47:18.844 27341-27341/prakash.pradyot.com.pinterestclone W/ArrayUtils: Ignoring invalid value asd
12-28 16:47:18.844 27341-27341/prakash.pradyot.com.pinterestclone W/ArrayUtils: Ignoring invalid value backlight
12-28 16:47:18.844 27341-27341/prakash.pradyot.com.pinterestclone W/ArrayUtils: Ignoring invalid value flowers
12-28 16:47:18.844 27341-27341/prakash.pradyot.com.pinterestclone W/ArrayUtils: Ignoring invalid value AR
12-28 16:47:18.852 27341-27341/prakash.pradyot.com.pinterestclone W/ArrayUtils: Ignoring invalid value manual
12-28 16:47:18.852 27341-27341/prakash.pradyot.com.pinterestclone W/ArrayUtils: Ignoring invalid value manual
12-28 16:47:18.852 27341-27341/prakash.pradyot.com.pinterestclone W/ArrayUtils: Ignoring invalid value emboss
12-28 16:47:18.852 27341-27341/prakash.pradyot.com.pinterestclone W/ArrayUtils: Ignoring invalid value sketch
12-28 16:47:18.852 27341-27341/prakash.pradyot.com.pinterestclone W/ArrayUtils: Ignoring invalid value neon
12-28 16:47:18.852 27341-27341/prakash.pradyot.com.pinterestclone W/ArrayUtils: Ignoring invalid value asd
12-28 16:47:18.852 27341-27341/prakash.pradyot.com.pinterestclone W/ArrayUtils: Ignoring invalid value backlight
12-28 16:47:18.852 27341-27341/prakash.pradyot.com.pinterestclone W/ArrayUtils: Ignoring invalid value flowers
12-28 16:47:18.852 27341-27341/prakash.pradyot.com.pinterestclone W/ArrayUtils: Ignoring invalid value AR
12-28 16:47:18.857 27341-27341/prakash.pradyot.com.pinterestclone I/CameraManager: Using legacy camera HAL.
12-28 16:47:18.864 27341-27529/prakash.pradyot.com.pinterestclone W/Camera: An error occurred while connecting to camera: 0
12-28 16:47:18.887 27341-27341/prakash.pradyot.com.pinterestclone W/ArrayUtils: Ignoring invalid value manual
12-28 16:47:18.887 27341-27341/prakash.pradyot.com.pinterestclone W/ArrayUtils: Ignoring invalid value manual
12-28 16:47:18.888 27341-27341/prakash.pradyot.com.pinterestclone W/ArrayUtils: Ignoring invalid value emboss
12-28 16:47:18.888 27341-27341/prakash.pradyot.com.pinterestclone W/ArrayUtils: Ignoring invalid value sketch
12-28 16:47:18.888 27341-27341/prakash.pradyot.com.pinterestclone W/ArrayUtils: Ignoring invalid value neon
12-28 16:47:18.888 27341-27341/prakash.pradyot.com.pinterestclone W/ArrayUtils: Ignoring invalid value asd
12-28 16:47:18.888 27341-27341/prakash.pradyot.com.pinterestclone W/ArrayUtils: Ignoring invalid value backlight
12-28 16:47:18.888 27341-27341/prakash.pradyot.com.pinterestclone W/ArrayUtils: Ignoring invalid value flowers
12-28 16:47:18.888 27341-27341/prakash.pradyot.com.pinterestclone W/ArrayUtils: Ignoring invalid value AR
12-28 16:47:18.903 27341-27341/prakash.pradyot.com.pinterestclone W/ArrayUtils: Ignoring invalid value manual
12-28 16:47:18.903 27341-27341/prakash.pradyot.com.pinterestclone W/ArrayUtils: Ignoring invalid value emboss
12-28 16:47:18.903 27341-27341/prakash.pradyot.com.pinterestclone W/ArrayUtils: Ignoring invalid value sketch
12-28 16:47:18.903 27341-27341/prakash.pradyot.com.pinterestclone W/ArrayUtils: Ignoring invalid value neon
12-28 16:47:18.903 27341-27341/prakash.pradyot.com.pinterestclone W/ArrayUtils: Ignoring invalid value asd
12-28 16:47:18.903 27341-27341/prakash.pradyot.com.pinterestclone W/ArrayUtils: Ignoring invalid value backlight
12-28 16:47:18.903 27341-27341/prakash.pradyot.com.pinterestclone W/ArrayUtils: Ignoring invalid value flowers
12-28 16:47:18.903 27341-27341/prakash.pradyot.com.pinterestclone W/ArrayUtils: Ignoring invalid value AR
12-28 16:47:18.912 27341-27341/prakash.pradyot.com.pinterestclone W/ArrayUtils: Ignoring invalid value manual
12-28 16:47:18.912 27341-27341/prakash.pradyot.com.pinterestclone W/ArrayUtils: Ignoring invalid value manual
12-28 16:47:18.912 27341-27341/prakash.pradyot.com.pinterestclone W/ArrayUtils: Ignoring invalid value emboss
12-28 16:47:18.912 27341-27341/prakash.pradyot.com.pinterestclone W/ArrayUtils: Ignoring invalid value sketch
12-28 16:47:18.912 27341-27341/prakash.pradyot.com.pinterestclone W/ArrayUtils: Ignoring invalid value neon
12-28 16:47:18.913 27341-27341/prakash.pradyot.com.pinterestclone W/ArrayUtils: Ignoring invalid value asd
12-28 16:47:18.913 27341-27341/prakash.pradyot.com.pinterestclone W/ArrayUtils: Ignoring invalid value backlight
12-28 16:47:18.913 27341-27341/prakash.pradyot.com.pinterestclone W/ArrayUtils: Ignoring invalid value flowers
12-28 16:47:18.913 27341-27341/prakash.pradyot.com.pinterestclone W/ArrayUtils: Ignoring invalid value AR
12-28 16:47:18.916 27341-27341/prakash.pradyot.com.pinterestclone I/CameraManager: Using legacy camera HAL.
12-28 16:47:18.920 27341-27532/prakash.pradyot.com.pinterestclone W/Camera: An error occurred while connecting to camera: 0

Can You Help Me With This?

**Comment by mistreckless** [comment]
@pradyotprksh Sorry, I don't support this library anymore
